#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi


if ! command -v golangci-lint &> /dev/null; then
    printf "installing golangci-lint"
    brew install golangci-lint
fi


PASS=true

for FILE in $STAGED_GO_FILES
do
  golangci-lint run $FILE
  if [[ $? == 1 ]]; then
    PASS=false
  fi
done

if ! $PASS; then
  printf "COMMIT FAILED\n"
  exit 1
else
  printf "COMMIT SUCCEEDED\n"
fi

exit 0
