name: golangci-lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "develop"
permissions:
  contents: read

jobs:
  golangci-lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Set up Go 1.24
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.0
        id: go
      - run: go version

      - name: Lint
        run: |
          # go get github.com/ethereum/go-ethereum/crypto/kzg4844
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.64.7
          ./bin/golangci-lint cache clean
          ./bin/golangci-lint run

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          # skip-go-installation: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
