name: tag-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: "ubuntu-latest"

    steps:
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - uses: actions/checkout@v2

      - name: Set env
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build & Publish the Docker image
        run: |
          docker buildx create --name builder --use --platform=linux/amd64  && docker buildx build --platform=linux/amd64 . -t us-docker.pkg.dev/covalent-project/network/bsp-agent:stable -t us-docker.pkg.dev/covalent-project/network/bsp-agent:"${{ env.TAG }}" --push

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          files: |
            *.zip
            *.tar.gz
